'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace GetSunat_CDR
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://service.sunat.gob.pe", ConfigurationName:="GetSunat_CDR.billService")>  _
    Public Interface billService
        
        'CODEGEN: El parámetro 'statusCdr' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatusCdr", ReplyAction:="http://service.sunat.gob.pe/billService/getStatusCdrResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStatusCdr(ByVal request As GetSunat_CDR.getStatusCdrRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="statusCdr")> GetSunat_CDR.getStatusCdrResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="urn:getStatusCdr", ReplyAction:="http://service.sunat.gob.pe/billService/getStatusCdrResponse")>  _
        Function BegingetStatusCdr(ByVal request As GetSunat_CDR.getStatusCdrRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetStatusCdr(ByVal result As System.IAsyncResult) As GetSunat_CDR.getStatusCdrResponse
        
        'CODEGEN: El parámetro 'status' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatus", ReplyAction:="http://service.sunat.gob.pe/billService/getStatusResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStatus(ByVal request As GetSunat_CDR.getStatusRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="status")> GetSunat_CDR.getStatusResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="urn:getStatus", ReplyAction:="http://service.sunat.gob.pe/billService/getStatusResponse")>  _
        Function BegingetStatus(ByVal request As GetSunat_CDR.getStatusRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetStatus(ByVal result As System.IAsyncResult) As GetSunat_CDR.getStatusResponse
    End Interface
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.sunat.gob.pe")>  _
    Partial Public Class statusResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private contentField() As Byte
        
        Private statusCodeField As String
        
        Private statusMessageField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=0)>  _
        Public Property content() As Byte()
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
                Me.RaisePropertyChanged("content")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property statusCode() As String
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
                Me.RaisePropertyChanged("statusCode")
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property statusMessage() As String
            Get
                Return Me.statusMessageField
            End Get
            Set
                Me.statusMessageField = value
                Me.RaisePropertyChanged("statusMessage")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusCdr", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusCdrRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public rucComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tipoComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public serieComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public numeroComprobante As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer)
            MyBase.New
            Me.rucComprobante = rucComprobante
            Me.tipoComprobante = tipoComprobante
            Me.serieComprobante = serieComprobante
            Me.numeroComprobante = numeroComprobante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusCdrResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusCdrResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public statusCdr As GetSunat_CDR.statusResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal statusCdr As GetSunat_CDR.statusResponse)
            MyBase.New
            Me.statusCdr = statusCdr
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatus", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public rucComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public tipoComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public serieComprobante As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public numeroComprobante As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer)
            MyBase.New
            Me.rucComprobante = rucComprobante
            Me.tipoComprobante = tipoComprobante
            Me.serieComprobante = serieComprobante
            Me.numeroComprobante = numeroComprobante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public status As GetSunat_CDR.statusResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal status As GetSunat_CDR.statusResponse)
            MyBase.New
            Me.status = status
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface billServiceChannel
        Inherits GetSunat_CDR.billService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getStatusCdrCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As GetSunat_CDR.statusResponse
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetSunat_CDR.statusResponse)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As GetSunat_CDR.statusResponse
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GetSunat_CDR.statusResponse)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class billServiceClient
        Inherits System.ServiceModel.ClientBase(Of GetSunat_CDR.billService)
        Implements GetSunat_CDR.billService
        
        Private onBegingetStatusCdrDelegate As BeginOperationDelegate
        
        Private onEndgetStatusCdrDelegate As EndOperationDelegate
        
        Private ongetStatusCdrCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegingetStatusDelegate As BeginOperationDelegate
        
        Private onEndgetStatusDelegate As EndOperationDelegate
        
        Private ongetStatusCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event getStatusCdrCompleted As System.EventHandler(Of getStatusCdrCompletedEventArgs)
        
        Public Event getStatusCompleted As System.EventHandler(Of getStatusCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetSunat_CDR_billService_getStatusCdr(ByVal request As GetSunat_CDR.getStatusCdrRequest) As GetSunat_CDR.getStatusCdrResponse Implements GetSunat_CDR.billService.getStatusCdr
            Return MyBase.Channel.getStatusCdr(request)
        End Function
        
        Public Function getStatusCdr(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer) As GetSunat_CDR.statusResponse
            Dim inValue As GetSunat_CDR.getStatusCdrRequest = New GetSunat_CDR.getStatusCdrRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Dim retVal As GetSunat_CDR.getStatusCdrResponse = CType(Me,GetSunat_CDR.billService).getStatusCdr(inValue)
            Return retVal.statusCdr
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetSunat_CDR_billService_BegingetStatusCdr(ByVal request As GetSunat_CDR.getStatusCdrRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements GetSunat_CDR.billService.BegingetStatusCdr
            Return MyBase.Channel.BegingetStatusCdr(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetStatusCdr(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As GetSunat_CDR.getStatusCdrRequest = New GetSunat_CDR.getStatusCdrRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Return CType(Me,GetSunat_CDR.billService).BegingetStatusCdr(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetSunat_CDR_billService_EndgetStatusCdr(ByVal result As System.IAsyncResult) As GetSunat_CDR.getStatusCdrResponse Implements GetSunat_CDR.billService.EndgetStatusCdr
            Return MyBase.Channel.EndgetStatusCdr(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetStatusCdr(ByVal result As System.IAsyncResult) As GetSunat_CDR.statusResponse
            Dim retVal As GetSunat_CDR.getStatusCdrResponse = CType(Me,GetSunat_CDR.billService).EndgetStatusCdr(result)
            Return retVal.statusCdr
        End Function
        
        Private Function OnBegingetStatusCdr(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim rucComprobante As String = CType(inValues(0),String)
            Dim tipoComprobante As String = CType(inValues(1),String)
            Dim serieComprobante As String = CType(inValues(2),String)
            Dim numeroComprobante As Integer = CType(inValues(3),Integer)
            Return Me.BegingetStatusCdr(rucComprobante, tipoComprobante, serieComprobante, numeroComprobante, callback, asyncState)
        End Function
        
        Private Function OnEndgetStatusCdr(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As GetSunat_CDR.statusResponse = Me.EndgetStatusCdr(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetStatusCdrCompleted(ByVal state As Object)
            If (Not (Me.getStatusCdrCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getStatusCdrCompleted(Me, New getStatusCdrCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getStatusCdrAsync(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer)
            Me.getStatusCdrAsync(rucComprobante, tipoComprobante, serieComprobante, numeroComprobante, Nothing)
        End Sub
        
        Public Overloads Sub getStatusCdrAsync(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer, ByVal userState As Object)
            If (Me.onBegingetStatusCdrDelegate Is Nothing) Then
                Me.onBegingetStatusCdrDelegate = AddressOf Me.OnBegingetStatusCdr
            End If
            If (Me.onEndgetStatusCdrDelegate Is Nothing) Then
                Me.onEndgetStatusCdrDelegate = AddressOf Me.OnEndgetStatusCdr
            End If
            If (Me.ongetStatusCdrCompletedDelegate Is Nothing) Then
                Me.ongetStatusCdrCompletedDelegate = AddressOf Me.OngetStatusCdrCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetStatusCdrDelegate, New Object() {rucComprobante, tipoComprobante, serieComprobante, numeroComprobante}, Me.onEndgetStatusCdrDelegate, Me.ongetStatusCdrCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetSunat_CDR_billService_getStatus(ByVal request As GetSunat_CDR.getStatusRequest) As GetSunat_CDR.getStatusResponse Implements GetSunat_CDR.billService.getStatus
            Return MyBase.Channel.getStatus(request)
        End Function
        
        Public Function getStatus(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer) As GetSunat_CDR.statusResponse
            Dim inValue As GetSunat_CDR.getStatusRequest = New GetSunat_CDR.getStatusRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Dim retVal As GetSunat_CDR.getStatusResponse = CType(Me,GetSunat_CDR.billService).getStatus(inValue)
            Return retVal.status
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetSunat_CDR_billService_BegingetStatus(ByVal request As GetSunat_CDR.getStatusRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements GetSunat_CDR.billService.BegingetStatus
            Return MyBase.Channel.BegingetStatus(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetStatus(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As GetSunat_CDR.getStatusRequest = New GetSunat_CDR.getStatusRequest()
            inValue.rucComprobante = rucComprobante
            inValue.tipoComprobante = tipoComprobante
            inValue.serieComprobante = serieComprobante
            inValue.numeroComprobante = numeroComprobante
            Return CType(Me,GetSunat_CDR.billService).BegingetStatus(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function GetSunat_CDR_billService_EndgetStatus(ByVal result As System.IAsyncResult) As GetSunat_CDR.getStatusResponse Implements GetSunat_CDR.billService.EndgetStatus
            Return MyBase.Channel.EndgetStatus(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetStatus(ByVal result As System.IAsyncResult) As GetSunat_CDR.statusResponse
            Dim retVal As GetSunat_CDR.getStatusResponse = CType(Me,GetSunat_CDR.billService).EndgetStatus(result)
            Return retVal.status
        End Function
        
        Private Function OnBegingetStatus(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim rucComprobante As String = CType(inValues(0),String)
            Dim tipoComprobante As String = CType(inValues(1),String)
            Dim serieComprobante As String = CType(inValues(2),String)
            Dim numeroComprobante As Integer = CType(inValues(3),Integer)
            Return Me.BegingetStatus(rucComprobante, tipoComprobante, serieComprobante, numeroComprobante, callback, asyncState)
        End Function
        
        Private Function OnEndgetStatus(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As GetSunat_CDR.statusResponse = Me.EndgetStatus(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetStatusCompleted(ByVal state As Object)
            If (Not (Me.getStatusCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getStatusCompleted(Me, New getStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getStatusAsync(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer)
            Me.getStatusAsync(rucComprobante, tipoComprobante, serieComprobante, numeroComprobante, Nothing)
        End Sub
        
        Public Overloads Sub getStatusAsync(ByVal rucComprobante As String, ByVal tipoComprobante As String, ByVal serieComprobante As String, ByVal numeroComprobante As Integer, ByVal userState As Object)
            If (Me.onBegingetStatusDelegate Is Nothing) Then
                Me.onBegingetStatusDelegate = AddressOf Me.OnBegingetStatus
            End If
            If (Me.onEndgetStatusDelegate Is Nothing) Then
                Me.onEndgetStatusDelegate = AddressOf Me.OnEndgetStatus
            End If
            If (Me.ongetStatusCompletedDelegate Is Nothing) Then
                Me.ongetStatusCompletedDelegate = AddressOf Me.OngetStatusCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetStatusDelegate, New Object() {rucComprobante, tipoComprobante, serieComprobante, numeroComprobante}, Me.onEndgetStatusDelegate, Me.ongetStatusCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
